[package]
name = "rust-crypto"
version = "0.1.0"
authors = []

[lib]
name = "rust-crypto"
path = "src/rust-crypto/lib.rs"

[[bin]]
name = "rust-crypto-util"
path = "src/rust-crypto-util/tool.rs"
test = false
bench = false

[profile.test]
opt-level = 2

[dependencies.time]
git = "https://github.com/rust-lang/time"
